# Generated by Django 6.0 on 2026-01-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notes',
            name='passcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
