# Generated by Django 6.0 on 2026-01-10 09:54

import notes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_notes_edit_notes_passcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='user',
        ),
        migrations.AddField(
            model_name='notes',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='2026-01-01 09:05:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notes',
            name='del_after',
            field=models.DateTimeField(default=notes.models.add_exp),
        ),
    ]
