# Generated by Django 6.0 on 2026-01-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_remove_notes_user_notes_created_notes_del_after'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='islocked',
            field=models.BooleanField(default=False),
        ),
    ]
