# Generated by Django 6.0 on 2026-01-11 05:26

import notes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_notes_islocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='del_after',
            field=models.DateTimeField(default=notes.models.add_exp, null=True),
        ),
    ]
