# Generated by Django 6.0 on 2026-01-11 05:28

import notes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_alter_notes_del_after'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='del_after',
            field=models.DateTimeField(default=notes.models.add_exp),
        ),
    ]
